# Generated by Django 3.2.2 on 2021-05-12 11:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseelementtext',
            name='Text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
