# Generated by Django 3.2.2 on 2021-05-12 11:45

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pyschool', '0002_alter_courseelementtext_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseElementVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', embed_video.fields.EmbedVideoField()),
                ('Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CourseInCourseElementLink', to='pyschool.course')),
                ('CourseSection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CourseSectionInCourseElementLink', to='pyschool.coursesection')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseElementLink',
        ),
    ]
