# Generated by Django 3.2.2 on 2021-05-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyschool', '0003_auto_20210512_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_decorations'),
        ),
    ]
