# Generated by Django 3.2.2 on 2021-05-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyschool', '0004_course_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
