# Generated by Django 3.2.2 on 2021-05-14 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyschool', '0005_course_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FOI', models.CharField(max_length=200)),
                ('Mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Group', models.CharField(blank=True, max_length=100, null=True)),
                ('UserDetailUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserDetailUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
