# Generated by Django 3.2.2 on 2021-05-15 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyschool', '0006_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='Role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CourseInUserCourse', to=settings.AUTH_USER_MODEL)),
                ('UserInCourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserInUserCourse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
