# Generated by Django 3.2.2 on 2021-05-15 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyschool', '0008_auto_20210516_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OwnerInCourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
