# Generated by Django 3.2.2 on 2021-05-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyschool', '0009_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users_profiles'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='Position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
