# Generated by Django 3.2.2 on 2021-05-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyschool', '0010_auto_20210516_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='GraduatedPlace',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
