# Generated by Django 3.2.2 on 2021-05-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyschool', '0012_userdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
