# Generated by Django 3.2.2 on 2021-05-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyschool', '0013_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseelementtext',
            name='Text',
            field=models.CharField(max_length=10000),
        ),
    ]
