# Generated by Django 3.2.2 on 2021-05-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyschool', '0014_alter_courseelementtext_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseSectionContentType', models.CharField(blank=True, max_length=100, null=True)),
                ('Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CourseInSectionContent', to='pyschool.course')),
                ('CourseSection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CourseSectionInSectionContent', to='pyschool.coursesection')),
                ('TextType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CourseElementTextInSectionContent', to='pyschool.courseelementtext')),
                ('VideoType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CourseElementVideoInSectionContent', to='pyschool.courseelementvideo')),
            ],
        ),
    ]
