# Generated by Django 3.2.2 on 2021-05-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyschool', '0016_coursesectioncontent_coursesectioncontentname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesectioncontent',
            name='CourseSectionContentName',
        ),
        migrations.AddField(
            model_name='courseelementtext',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courseelementvideo',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
